[[redirects]]
  from = "/contact-tracing-strategy-in-south-korea"
  to = "/more-resources/contact-tracing-strategy"

[[redirects]]
  from = "/covid-19-test-site-installation-guide"
  to = "/more-resources/test-site-installation-guide"

[[redirects]]
  from = "/drive-thru-manuals"
  to = "/kcdc-guidelines/drive-thru-manuals"

[[redirects]]
  from = "/management-of-healthcare-facilities-with-confirmed-cases"
  to = "/kcdc-guidelines/management-of-healthcare-facilities-with-confirmed-cases"

[[redirects]]
  from = "/screening-center-operation-guide"
  to = "/kcdc-guidelines/screening-center-operation-guide"

[[redirects]]
  from = "/kcdc-covid-19-response-guidelines"
  to = "/kcdc-guidelines/response-guidelines-for-local-governments"

[[redirects]]
  from = "/kcdc-covid-19-response-guidelines/more-languages"
  to = "/kcdc-guidelines/response-guidelines-for-local-governments"

[[redirects]]
  from = "/kcdc-guidelines/routine-distancing-guidelines"
  to = "/more-resources/routine-distancing-guidelines"
